# -*- coding: utf-8 -*-
<MainWindow>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"

        Label:
            text: str(root.counter)
            font_size: 40

        Button:
            text: "\u0443\u0432\u0435\u043B\u0438\u0438\u0442\u044C \u0441\u0447\u0435\u0442\u0447\u0438\u043A"
            on_press: root.increase()
            font_size: 40